import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { defs } from '../defs'
import { decodePayload } from '../decode'
import { FrameParser } from '../frame'
import expected from './fixtures/frames.expected.json'

/**
 * Integration test: `frames.bin`/`frames.expected.json` are generated by
 * `scripts/gen-fixtures.py` from real pymavlink encode/decode calls,
 * independent of anything in this codebase. This proves our hand-written
 * FrameParser + decodePayload agree with pymavlink's own reference
 * implementation byte-for-byte and field-for-field, not just with our own
 * encodeFrame()'s round trip (frame.test.ts/decode.test.ts already cover
 * that in isolation).
 */
const frameBytes = new Uint8Array(
  readFileSync(join(process.cwd(), 'src/core/mavlink/__tests__/fixtures/frames.bin')),
)

/** Compares a decoded field value against the fixture's JSON representation
 * (64-bit fields are stored as decimal strings there, see gen-fixtures.py). */
function expectFieldEqual(actual: unknown, expectedValue: unknown): void {
  if (Array.isArray(actual)) {
    const expectedArray = expectedValue as unknown[]
    expect(actual).toHaveLength(expectedArray.length)
    actual.forEach((v, i) => expectFieldEqual(v, expectedArray[i]))
  } else if (typeof actual === 'bigint') {
    expect(actual.toString()).toBe(String(expectedValue))
  } else {
    expect(actual).toBe(expectedValue)
  }
}

describe('MAVLink fixtures (pymavlink-generated, decisions-m1)', () => {
  it('parses every fixture frame in order, with zero resync errors', () => {
    const parser = new FrameParser(defs)
    const frames = parser.push(frameBytes)

    expect(frames).toHaveLength(expected.frames.length)
    expect(parser.stats).toEqual({
      received: expected.frames.length,
      crcErrors: 0,
      badMsgId: 0,
      dropped: 0,
    })
  })

  it.each(expected.frames.map((f, i) => [`${i}: ${f.msgname} (v${f.version}, seq=${f.seq})`, i, f] as const))(
    'frame %s matches pymavlink: header fields, wire payload, and decoded fields',
    (_label, index, exp) => {
      const parser = new FrameParser(defs)
      const frames = parser.push(frameBytes)
      const frame = frames[index]

      expect(frame.version).toBe(exp.version as 1 | 2)
      expect(frame.msgid).toBe(exp.msgid)
      expect(frame.seq).toBe(exp.seq)
      expect(frame.sysid).toBe(exp.sysid)
      expect(frame.compid).toBe(exp.compid)
      expect(Buffer.from(frame.payload).toString('hex')).toBe(exp.payloadHex)

      const decoded = decodePayload(defs, frame)
      expect(decoded.name).toBe(exp.msgname)
      for (const [name, value] of Object.entries(exp.fields)) {
        expectFieldEqual(decoded.fields[name], value)
      }
    },
  )
})
