import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { defs } from '../defs'
import { decodePayload } from '../decode'
import { FrameParser } from '../frame'
import expected from './fixtures/frames-m2.expected.json'

/**
 * Integration test for the Task 5.3 (M2) companion fixture pair --
 * `frames-m2.bin`/`frames-m2.expected.json`, generated by the same
 * `scripts/gen-fixtures.py` as `fixtures.test.ts`'s M1 pair, from real
 * pymavlink encode/decode calls. Kept as a separate file/describe block
 * (not appended to frames.bin) because router.test.ts's M1 integration test
 * asserts the exact ordered list of message names in frames.bin -- see
 * gen-fixtures.py's module doc.
 *
 * Covers the M2 telemetry set (ATTITUDE/SYS_STATUS/GPS_RAW_INT/
 * RC_CHANNELS/SERVO_OUTPUT_RAW/HEARTBEAT, including their documented
 * "unknown" sentinel values), the inbound ACCELCAL_VEHICLE_POS COMMAND_LONG
 * (one per face + success/failure), MAG_CAL_PROGRESS/MAG_CAL_REPORT (two
 * compasses), and the DO_MOTOR_TEST COMMAND_ACK.
 */
const frameBytes = new Uint8Array(
  readFileSync(join(process.cwd(), 'src/core/mavlink/__tests__/fixtures/frames-m2.bin')),
)

/** Compares a decoded field value against the fixture's JSON representation
 * (64-bit fields are stored as decimal strings there, see gen-fixtures.py). */
function expectFieldEqual(actual: unknown, expectedValue: unknown): void {
  if (Array.isArray(actual)) {
    const expectedArray = expectedValue as unknown[]
    expect(actual).toHaveLength(expectedArray.length)
    actual.forEach((v, i) => expectFieldEqual(v, expectedArray[i]))
  } else if (typeof actual === 'bigint') {
    expect(actual.toString()).toBe(String(expectedValue))
  } else {
    expect(actual).toBe(expectedValue)
  }
}

describe('MAVLink M2 fixtures (pymavlink-generated, task 5.3)', () => {
  it('parses every fixture frame in order, with zero resync errors', () => {
    const parser = new FrameParser(defs)
    const frames = parser.push(frameBytes)

    expect(frames).toHaveLength(expected.frames.length)
    expect(parser.stats).toEqual({
      received: expected.frames.length,
      crcErrors: 0,
      badMsgId: 0,
      dropped: 0,
    })
  })

  it.each(expected.frames.map((f, i) => [`${i}: ${f.msgname} (v${f.version}, seq=${f.seq})`, i, f] as const))(
    'frame %s matches pymavlink: header fields, wire payload, and decoded fields',
    (_label, index, exp) => {
      const parser = new FrameParser(defs)
      const frames = parser.push(frameBytes)
      const frame = frames[index]

      expect(frame.version).toBe(exp.version as 1 | 2)
      expect(frame.msgid).toBe(exp.msgid)
      expect(frame.seq).toBe(exp.seq)
      expect(frame.sysid).toBe(exp.sysid)
      expect(frame.compid).toBe(exp.compid)
      expect(Buffer.from(frame.payload).toString('hex')).toBe(exp.payloadHex)

      const decoded = decodePayload(defs, frame)
      expect(decoded.name).toBe(exp.msgname)
      for (const [name, value] of Object.entries(exp.fields)) {
        expectFieldEqual(decoded.fields[name], value)
      }
    },
  )
})
